### ISSUE TITLE
RA-HMD reproduce issue

### ISSUE THREAD

**Issue by happywinder** [JingbiaoMei/RGCL#10]
I follow your instructions 
git clone https://github.com/JingbiaoMei/RGCL.git
cd RGCL

# Initialize and update submodules
git submodule update --init --recursive

# Navigate to the LLaMA-Factory submodule
cd RA-HMD/LLAMA-FACTORY
conda create -n llamafact python=3.10 -y
conda activate llamafact
pip install -e ".[torch,metrics,deepspeed,liger-kernel,bitsandbytes,qwen]"
pip install torchmetrics wandb easydict
pip install qwen_vl_utils torchvision
# Install FAISS
conda install -c pytorch -c nvidia faiss-gpu=1.7.4 mkl=2021 blas=1.0=mkl -y

**When I excute bash scripts 
bash /home/xk/RGCL/RA-HMD/LLAMA-FACTORY-Ver202512/my_scripts/memes/hm/qwen2vl-7b-hm-classifier_qlora.sh**
it error with text" [rank1]: Traceback (most recent call last):
[rank1]:   File "/home/xk/anaconda3/envs/LLaMA-Factory/lib/python3.10/site-packages/llamafactory/launcher.py", line 180, in <module>
[rank1]:     run_exp()
[rank1]:   File "/home/xk/anaconda3/envs/LLaMA-Factory/lib/python3.10/site-packages/llamafactory/train/tuner.py", line 110, in run_exp
[rank1]:     _training_function(config={"args": args, "callbacks": callbacks})
[rank1]:   File "/home/xk/anaconda3/envs/LLaMA-Factory/lib/python3.10/site-packages/llamafactory/train/tuner.py", line 82, in _training_function
[rank1]:     raise ValueError(f"Unknown task: {finetuning_args.stage}.")
[rank1]: ValueError: Unknown task: sft-classifier.
[INFO|2025-12-22 19:16:24] llamafactory.hparams.parser:423 >> Process rank: 3, world size: 4, device: cuda:3, distributed training: True, compute dtype: torch.bfloat16
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/xk/anaconda3/envs/LLaMA-Factory/lib/python3.10/site-packages/llamafactory/launcher.py", line 180, in <module>
[rank3]:     run_exp()
[rank3]:   File "/home/xk/anaconda3/envs/LLaMA-Factory/lib/python3.10/site-packages/llamafactory/train/tuner.py", line 110, in run_exp
[rank3]:     _training_function(config={"args": args, "callbacks": callbacks})
[rank3]:   File "/home/xk/anaconda3/envs/LLaMA-Factory/lib/python3.10/site-packages/llamafactory/train/tuner.py", line 82, in _training_function
[rank3]:     raise ValueError(f"Unknown task: {finetuning_args.stage}.")
[rank3]: ValueError: Unknown task: sft-classifier."

**Comment by JingbiaoMei** [comment]
I have reproduced and found the code working fine. 
Could you check if your Llamafactory points correctly to the actual install?
pip list | grep llamafactory
llamafactory             0.9.4.dev0  ....RGCL/RA-HMD/LLAMA-FACTORY-Ver202512

**Comment by happywinder** [comment]
I'm sorry to bother you. I'm currently trying to reproduce the results with **Qwen2.5-VL**. I have recreated a fresh environment and followed the instructions below:

```bash
git clone https://github.com/JingbiaoMei/RGCL.git
cd RGCL

# Initialize and update submodules
git submodule update --init --recursive

# Navigate to the LLaMA-Factory submodule
cd RA-HMD/LLAMA-FACTORY
conda create -n llamafact python=3.10 -y
conda activate llamafact
pip install -e ".[torch,metrics,deepspeed,liger-kernel,bitsandbytes,qwen]"
pip install torchmetrics wandb easydict
pip install qwen_vl_utils torchvision
# Install FAISS
conda install -c pytorch -c nvidia faiss-gpu=1.7.4 mkl=2021 blas=1.0=mkl -y
```

Then, I modified the config file at  
`/home/xk/RGCL/RA-HMD/LLAMA-FACTORY/my_configs/memes/hm/qwen2vl-7B_qlora_classifier.yaml`  
by updating the model path as follows:

```yaml
model_name_or_path: /data/oldhome/xk/Qwen/Qwen2.5-VL-7B-Instruct
```

After that, I ran the command:  
```bash
CUDA_VISIBLE_DEVICES=0 bash '/home/xk/RGCL/RA-HMD/LLAMA-FACTORY/my_scripts/memes/hm/qwen2vl-7b-hm-classifier_qlora.sh'
```

Below is my `pip list` output:

*(The full pip list you provided is included here for reference—omitted in translation for brevity but retained in context.)*

Notably:
- `llamafactory 0.9.3.dev0` (installed in editable mode from the local path)
- `transformers 4.51.3`
- `liger_kernel 0.6.4`
- `torch 2.9.1`

I tried different versions of `transformers`, but each leads to a different error:

---

**With `transformers==4.51.0`:**
```python
Traceback (most recent call last):
  ...
  File ".../transformers/trainer.py", line 2627, in _inner_training_loop
    self._maybe_log_save_evaluate(
TypeError: CustomSeq2SeqRegressionTrainer._maybe_log_save_evaluate() got an unexpected keyword argument 'learning_rate'
```

---

**With `transformers==4.50.0`:**
```python
Traceback (most recent call last):
  ...
  File ".../liger_kernel/transformers/model/qwen2_vl.py", line 8, in <module>
    from transformers.utils import can_return_tuple
ImportError: cannot import name 'can_return_tuple' from 'transformers.utils'
```

---

I would greatly appreciate your help in identifying a compatible `transformers` version (or necessary fixes) that works with Qwen2.5-VL in this LLaMA-Factory setup.

**Comment by happywinder** [comment]
I I’ve successfully launched the Qwen2.5-VL experiment using LLaMA-Factory (version 0.9.4.dev0). The training is now running smoothly, and I’m looking forward to seeing the results!
